- name: install requirements packages
  yum:
    name:
      - epel-release
      - conntrack  
      - ipvsadm 
      - ntp 
      - ntpdate 
      - ipset 
      - jq 
      - iptables 
      - curl 
      - sysstat 
      - libseccomp
    state: present
- name: install keepalived for master
  yum: 
    name:
      - keepalived
    state: present
  when: role == 'master' and keepalived  == 'true'
- name: kernel setting
  sysctl:
    name: "{{item.0}}"
    value: "{{item.1}}"
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: no
    state: present
  with_list:
    - ["net.ipv4.tcp_keepalive_time", 600]
    - ["net.ipv4.tcp_keepalive_intvl", 30]
    - ["net.ipv4.tcp_keepalive_probes", 10]
    - ["net.ipv6.conf.all.disable_ipv6", 1]
    - ["net.ipv6.conf.default.disable_ipv6", 1]
    - ["net.ipv6.conf.lo.disable_ipv6", 1]
    - ["net.ipv4.neigh.default.gc_stale_time", 120]
    - ["net.ipv4.conf.all.rp_filter", 0]
    - ["net.ipv4.conf.default.rp_filter", 0]
    - ["net.ipv4.conf.default.arp_announce", 2]
    - ["net.ipv4.conf.lo.arp_announce", 2]
    - ["net.ipv4.conf.all.arp_announce", 2]
    - ["net.ipv4.ip_forward", 1]
    - ["net.ipv4.tcp_tw_recycle", 0]
    - ["net.ipv4.tcp_max_tw_buckets", 5000]
    - ["net.ipv4.tcp_syncookies", 1]
    - ["net.ipv4.tcp_max_syn_backlog", 1024]
    - ["net.ipv4.tcp_synack_retries", 2]
    - ["net.bridge.bridge-nf-call-ip6tables", 1]
    - ["net.bridge.bridge-nf-call-iptables", 1]
    - ["net.netfilter.nf_conntrack_max", 2310720]
    - ["fs.inotify.max_user_watches", 1048576]
    - ["fs.inotify.max_user_instances", 8192]
    - ["fs.may_detach_mounts", 1]
    - ["fs.file-max", 52706963]
    - ["fs.nr_open", 52706963]
    - ["net.bridge.bridge-nf-call-arptables", 1]
    - ["vm.swappiness", 0]
    - ["vm.overcommit_memory", 1]
    - ["vm.panic_on_oom", 0]
- name: modprobe ipvs modules
  modprobe:
    name: "{{item}}"
    state: present
  with_items:
    - "ip_vs"
    - "ip_vs_rr"
    - "ip_vs_wrr"
    - "ip_vs_sh"
    - "nf_conntrack_ipv4"
    - "br_netfilter"
- name: Set the policy for the FORWARD chain to ACCEPT
  iptables:
    chain: FORWARD
    policy: ACCEPT
- name: iptables flush filter
  iptables:
    chain: "{{ item }}"
    flush: yes
  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]
- name: iptables flush nat
  iptables:
    table: nat
    chain: '{{ item }}'
    flush: yes
  with_items: [ 'INPUT', 'OUTPUT', 'PREROUTING', 'POSTROUTING' ]
- name: setting timezone
  shell: "timedatectl set-timezone Asia/Shanghai && timedatectl set-local-rtc 0"
- name: restart rsyslog service
  service:
    name: rsyslog
    state: restarted
- name: restart crond service
  service:
    name: crond
    state: restarted
- name: cp ntp.conf file
  template:
    src: "{{ansible_root}}/roles/kubernetes/install_kube_node/templates/ntp.conf.j2"
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: '0644'
- name: start ntpd server
  service:
    name: ntpd
    state: restarted
    enabled: yes
